### PR TITLE
Treat MANAGED_SHALLOW_CLONE as a table

### LINKED ISSUE #601: Bug: Delta Clones unsupported by `DatabricksRelationType`
### Describe the bug

Sources do not have support for [Databricks clones](https://docs.databricks.com/en/sql/language-manual/delta-clone.html) in [DatabricksRelationType](https://github.com/databricks/dbt-databricks/blob/1d21b328fd2ca57cabe0b8bd2dd09fdbcc884a3b/dbt/adapters/databricks/relation.py#L31-L37)

### Steps To Reproduce

I've encountered this issue in a few places but most recently using the [dbt-labs/dbt-codegen](https://github.com/dbt-labs/dbt-codegen) package. Specifically:
```sh
dbt run-operation generate_source --args '{
        "schema_name": "my_schema",
        "database_name": "my_source"
    }'
```

### Expected behavior

Should return correct source definition yaml

### Screenshots and log output

Screenshot 2024-03-01 at 4 48 14 PM

### PR DESCRIPTION
**Pull request by benc-db**
Resolves #601

### Description

MANAGED_SHALLOW_CLONE is a new type that we were not handling.  The aim with this PR is a.) to stop 'interpreting' the table type when making the catalog, and b.) treat clones as tables for performing dbt operations.

### Checklist

- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.

### CODE REVIEW

File: dbt/include/databricks/macros/adapters/metadata.sql [hunk 1]
```diff
@@ -94,48 +94,11 @@
   {% do return(load_result('get_view_description_alt').table) %}
 {% endmacro %}
 
-
-{% macro get_uc_tables_with_columns(relation) %}
```
Comment (benc-db) [inline dbt/include/databricks/macros/adapters/metadata.sql:98]: After I created this macro, I stopped using it.  Cleaning it up.

**Review by jackyhu-db — APPROVED** [review]
