### PR TITLE
fix: quote catalog names in SHOW SCHEMAS commands (#1325)

### LINKED ISSUE #1325: Catalog names with hyphens not properly quoted in SHOW SCHEMAS commands Github Actions
### Describe the bug
When using a Unity Catalog name containing hyphens (or other special characters that require quoting), dbt-databricks generates unquoted SQL in `SHOW SCHEMAS` commands, causing failures on Github Actions.

### Steps To Reproduce
1. Use a Unity Catalog with hyphens in the name (e.g., `data_engineering-uc-dev`)
2. Configure dbt profile with this catalog
3. Run `dbt test` or any command that checks for schema existence

### Expected behavior
Catalog identifiers should be automatically quoted with backticks:
SHOW SCHEMAS IN 'data_engineering-uc-dev' LIKE 'schema_name'

### Actual behavior
SHOW SCHEMAS IN data_engineering-uc-dev LIKE 'schema_name'

### Screenshots and log output

Encountered an error:
Database Error
  Database Error

[INVALID_IDENTIFIER] The unquoted identifier data_engineering-uc-dev is invalid 
and must be back quoted as: 'data_engineering-uc-dev'.
Unquoted identifiers can only contain ASCII letters ('a' - 'z', 'A' - 'Z'), digits ('0' - '9'), 
and underbar ('_'). Unquoted identifiers must also not start with a digit.
Different data sources and meta stores may impose additional restrictions on valid[INVALID_IDENTIFIER] The unquoted identifier data_engineering-uc-dev is invalid 
'data_engineering-uc-dev'.
Unquoted identifiers can only contain ASCII letters ('a' - 'z', 'A' - 'Z'), digits ('0' - '9'), 
and underbar ('_'). Unquoted identifiers must also not start with a digit.
Different data sources and meta stores may impose additional restrictions on valid

### System information
**The output of `dbt --version`:**

  - installed: 1.11.2
Plugins:
  - databricks: 1.11.4 - Up to date!
  - spark:      1.10.1 - Up to date!

**The operating system you're using:** 
macos

**The output of `python --version`:** 
Python 3.11.11

### PR DESCRIPTION
**Pull request by aarushisingh04**
resolves #1325

### Description

when a unity catalog name contains hyphens or other special characters (e.g., `data_engineering-uc-dev`), `SHOW SCHEMAS` commands fail with `INVALID_IDENTIFIER` because the catalog name is not quoted.

**fix:** added backtick quoting around `{{ database }}` in the `list_schemas_sql` and `check_schema_exists_sql` macros in `metadata.sql`.

**before:**
```sql
SHOW SCHEMAS IN data_engineering-uc-dev
```

**after:**
```sql
SHOW SCHEMAS IN `data_engineering-uc-dev`
```

added 4 unit tests covering normal, hyphenated, and null database names for both macros.

### Checklist

- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-databricks next" section.

### CODE REVIEW

File: dbt/include/databricks/macros/adapters/metadata.sql [hunk 1]
```diff
@@ -33,7 +33,7 @@ SHOW TABLES IN {{ relation.render() }}
 
 {% macro list_schemas_sql(database) %}
 {% if database %}
-  SHOW SCHEMAS IN {{ database }}
+  SHOW SCHEMAS IN `{{ database }}`
```
Comment (sd-db) [inline dbt/include/databricks/macros/adapters/metadata.sql]: nit: can we use `adapter.quote()` instead of raw back-ticks "``". It is the preferred practice in the codebase and protects against double-quoting. I think without it might also be fine here but is recommended and a smallish change.

Comment (aarushisingh04) [reply dbt/include/databricks/macros/adapters/metadata.sql]: @sd-db thanks for the check, it's done.

**Review by sd-db — APPROVED** [review]
Thanks for the PR !!

**Comment by aarushisingh04** [comment]
@mstfkmlbsbdk2023 happy to help 👍
